### PR TITLE
Feature/185  specialized form inputs

### PR DESCRIPTION
**Pull request by kevinmpowell**
To test:
1. Switch to `/library`
2. `npm install`
3. `gulp`
4. Navigate to `/sink-pages/components/forms.html`

Scroll all the way to the bottom to view date & telephone mask examples.

### CODE REVIEW

**Comment by jamesmelzer** [comment]
Both work well. Approved as-is. 

The plugin ignores typed slashes, dashes, and parentheses! Yay! 

My only concern is a usability one. The mask is a placeholder, and it feels like it it should stay in placeholder styling while the user types over it in data styling. Put another way, when my state is 05/1D/YYYY, I should be able to tell the 1 is data and the D is placeholder, like *05/1*D/YYYY. I don't think this is a deal-breaker by any means (again - we don't see this degree of masking often), but it might enhance the usability. 

I imagine this isn't the way the plugin is set up (nor is it the way JDRF's current state is set up), and would require rearchitecting the whole thing. But, I thought I'd bring it up, so that:
- @patrickmckowen can ponder its priority for a future refactor
- @kevinmpowell can respond about feasibility

**Comment by kevinmpowell** [comment]
> * @kevinmpowell can respond about feasibility

That was the first thing I tried to change but because the mask _is_ the editable content area there's no way to make it a separate color. This is the same way the current jQuery plugin works on the jdrf site today.

**Comment by jamesmelzer** [comment]
I suspected as much, but figured you’d know for sure. Thanks.
-- 
James Melzer

EightShapes, LLC
james@eightshapes.com
301-651-7719

**Comment by joesnellpdx** [comment]
@patrickmckowen @ismaeltoure7 

This branch already exists with an input mask - built by Kevin but not approved / merged at the time.

- Pull this branch
- In library run `npm install`
- IN library run `gulp`
- see the bottom of this page: `/sink-pages/components/forms.html

Additions made:
- additional text to define on sink page
- MM/YY mask (I see used in CC forms)

Questions:
1. Does this behave as expected?
2. See placeholder font color and weight for mask - should weight match text state OR keep to match existing placeholder fonts?

**Comment by patrickmckowen** [comment]
@lauralvictor once the design and code is approved (wait to hear from Ismael and Joe) please cross-browser QA.  Check with Ismael if you have questions about the intended UX.

**Comment by joesnellpdx** [comment]
@ismaeltoure7 

- All masks lowercase
- I could not replicate this - should be `mm/yy` - active `10/19`. If I am missing something, please provide more detail. 
- Added `inputmode="numeric" pattern="[0-9]*"` for CC Expiration and Date input mask fields

@patrickmckowen 

- For doc-site, I need to ping Kevin for assistance. I tried quick to rig it up, but got some errors. I think it is likely a simple question of where to place the npm dependencies. Before I ping him, I need your approval. 
- The way it is setup, properties consuming Spirit will have to install and setup the npm package locally (this is per our standards set early on with little or no js coming through as part of Spirit). 
- On the doc site, there is an external dependencies section. I think I should add this dependency here as well once we confirm this will remain an external dependency and I get advice from Kevin on doc-site. 

For reference, here is the npm package:
https://www.npmjs.com/package/inputmask

**Comment by joesnellpdx** [comment]
@patrickmckowen 

Screencast of latest added to wrike:
https://www.wrike.com/workspace.htm?view=task&acc=1797000#path=folder&id=291605987&t=302018591&a=1797000

**Comment by lauralvictor** [comment]
@ismaeltoure7 Is any further action required from me on this?

**Comment by joesnellpdx** [comment]
@ismaeltoure7 nope. you are relieved!

**Comment by joesnellpdx** [comment]
@kevinmpowell 

Hey Kevin! Long time no talk!

I need your assistance / advice. 

For the masking of inputs in this ticket, I moved your previous work forward a little.

It is approved and ready to go from a library standpoint - see files changed.

We are thinking of adding or creating a spirit.js  and spirit.min.js files as part of the npm package.

I do not think this was ever set up.

1) How do I put the npm package and control for these scripts into a directory that will generate the cdn url for spirit.min.js?

2) I tried getting these script to work as part of just the library / doc_site - but ran into errors on the doc site. I need advice / direction here so I can achieve this in the future. 

3) Should other scripts be included? On .org currently, we are copying from the library scripts for accordions, local nav, vertical nav, and card grid.  

I know we want the scripts provided by Spirit to be limited, but we also want the ability for developers and vendors from other agencies to be able to scaffold from Spirit without a large lift of custom scripting if possible. I thought we had a definition of where that _line_ was, but I do not see it in the documentation. 

Main questions - reiterating:
1) How do I get the npm package and control for the masks into the doc_site and the cdn?
2) How do I add a package / control for use on only the library and doc_site - not npm correctly?
2) What are your thoughts on existing / future scripts to be included / excluded? 

Here are a couple reference docs that I think are now a bit outdated:
https://docs.google.com/document/u/1/d/1f76_iPS3gfiHiKIU93XVHPOjHZwSmu5EhhsluXXPI3Y/edit
https://docs.google.com/document/d/1izGQJbckd99tjsSO63f1ExUanFH7ox5gRJwG9V2bSRg/edit

LMK if you have further questions. Happy to hop one a video chat and/or converse in the Slack channel.

**Comment by lauralvictor** [comment]
@joesnellpdx I am attempting to view this branch in Browserstack to perform cross-browser testing. But I receive the following errors when I run gulp. Do I need to make any changes to my settings locally, or is there something that needs to be resolved on this feature branch? (Note: I am not receiving this error when I run gulp on "develop" branch or other feature branches.)

****Error: File not found with singular glob: /Users/lvictor/Desktop/spirit-github/spirit/library/node_modules/inputmask/dist/inputmask/dependencyLibs/inputmask.dependencyLib.js (if this was purposeful, use `allowEmpty` option)**

[gulp-error.txt](https://github.com/JDRF/spirit/files/2788304/gulp-error.txt)**

**Comment by joesnellpdx** [comment]
@lauralvictor 

Follow these steps:
**https://github.com/JDRF/spirit/pull/279#issuecomment-454969259**

Steps also in description of MR

Let me know if you still have issues

**Comment by lauralvictor** [comment]
@joesnellpdx I've completed browser testing, and have encountered an issue only in Firefox browsers. For FF in MacOS, Windows 10/8.1, and on Android, when a user enters a validly-formatted date or tel # in the appropriate field, the error formatting is displaying. When the user selects the field, the error message displays "Please match the requested format". I've attached screengrabs of each instance.


bs_realdroid_mobile_samsung galaxy s9 plus-8 0-1440x2960
bs_macmo_firefox_64 0
bs_win10_firefox_64 0

**Comment by joesnellpdx** [comment]
@lauralvictor  pushed an update to set a regex pattern for xbrowser. 

Please retest. 

SEE the following for changes: 
https://github.com/JDRF/spirit/pull/279/commits/586c8cf3642dbbdf9f7fdd46ab44db0133dd6101
https://github.com/JDRF/spirit/pull/279/commits/0cbc3320d1a70b63a63305a434f4b857060ebe19

**Comment by lauralvictor** [comment]
@joesnellpdx Sorry, I've retested and am still seeing this error occurring on moblie FF, as well as MAcOS and Win10/8.1
bs_realdroid_mobile_samsung galaxy s9 plus-8 0-1440x2960 1

**Comment by joesnellpdx** [comment]
@patrickmckowen 
@lauralvictor 

I have pushed an update, but the solution is not ideal.
On FF, the field with throw an error is set to be numeric (for keyboard purposes) yet any NON numeric values are in the field (i.e. `/` for dates). Therefore, we cannot force the numeric keyboard on either the phone or date masks based on what I've found.

I have spend a couple hours either trying to resolve this with the existing options or seeking an alternative. I have not found a viable alternative. 

There are also the options of using input types 'tel' and 'date' --- but that changes things a lot depending on browser PLUS probably will not work with Hotjar anyways.

Seeking direction here.
I feel like using the mask we need to be okay without the numeric keyboard for the time being?

**Comment by lauralvictor** [comment]
@joesnellpdx I will defer to @patrickmckowen regarding the decision of not using the numeric keyboard.

**Comment by joesnellpdx** [comment]
@patrickmckowen @ismaeltoure7 @lauralvictor 

I agree. We can always revisit later as browsers, other scripts, + Hotjar evolve.

**Comment by ismaeltoure7** [comment]
@patrickmckowen @joesnellpdx @lauralvictor I am okay with the proposed solution.

**Comment by joesnellpdx** [comment]
@lauralvictor 

Waiting for review here

**Comment by lauralvictor** [comment]
@joesnellpdx I have retested and conformed your fix works on FF now, as well as other browsers/devices. I approve these changes

**Pull request merged**
