### PR TITLE
Add depth visual style doc page

### PR DESCRIPTION
**Pull request by kevinmpowell**

### CODE REVIEW

**Comment by kevinmpowell** [comment]
> Thanks! @kevinmpowell, @joesnellpdx recently updated the box-shadow values (#342). Will this page be updated once those updates are merged?

Good question @ismaeltoure7, I've left feedback on @joesnellpdx's issue and this page would likely need to be modified if token changes are made. I'll keep an eye on #342 and won't merge this until after it's completed.

**Comment by kevinmpowell** [comment]
@ismaeltoure7 and @joesnellpdx I've updated this doc based on @joesnellpdx's latest elevation token/mixin work. Please review and approve if it looks good.

**Comment by ismaeltoure7** [comment]
@kevinmpowell I am no longer seeing the examples from the sink page
screen shot 2019-02-25 at 9 21 35 am

**Comment by kevinmpowell** [comment]
> @kevinmpowell I am no longer seeing the examples from the sink page

@ismaeltoure7 try rebuilding `library`:
`cd library && gulp`

Then `ctrl + C` to quit library and run `doc-site`:
`cd doc-site && gulp`

Let me know if that doesn't work.

**Pull request merged**
