### PR TITLE
Feature/281 lft mobile spacing

### PR DESCRIPTION
**Pull request by joesnellpdx**
Before reviewing code - I am assigning @patrickmckowen and @ismaeltoure7 to review styles and compare to sketch.

Changes within long-form-text:

- set 'style' breakpoint at `$spirit-breakpoint-m` (768px)
- reduce padding / margin on headings on mobile
- update styles for blockquote, image, video, object, picture, figure

NOTES:
Existing styles from WIP (work in progress) ticket that was merged included styles for 'float items' that does not match sketch (in sketch, it appears all items are 100% width until breakpoint - then 50% width):
- width: 352px;
- max-width: 50%;

Sketch shows margin top for headings - should be padding top for headings in sketch per previous changes in development - ONLY for headings. 

To view changes:
In library:
- Checkout this branch
- Pull
- Run `gulp`
- go to the long-form text sink and view the first section (white background)
`/sink-pages/components/long-form-text.html`

### CODE REVIEW

**Comment by ismaeltoure7** [comment]
@joesnellpdx 
768px is correct for the breakpoint. I am not sure about the intentions behind the floats but happy to jump on a call in to morning to discuss, along with the other issues I listed.

**Comment by joesnellpdx** [comment]
Per discussion with @ismaeltoure7 

1. Define heading combinators vs lead headings
2. Make 'floated' items width 100% (default) at smaller screens. Apply float at 768 breakpoint. Keep 50% / 352px width for now as we aren't sure where they are coming from.
3. Other questions answered / clarified

Per discussion: these updates were in a WIP (work in progress) branch by James that made it into master - so you will see the previous version of the floated items on .org.

Additionally: on .org - Wordpress is using the default align classes (`.alignleft`) rather than `.spirit-pull-quote-left` or` .spirit-image-left` in custom css. 

Will update comments when ready to re-review

CC: @patrickmckowen

**Comment by joesnellpdx** [comment]
@patrickmckowen @ismaeltoure7 

Made the adjustments from the previous comment including:

- use reusable blocks for sink output (content)
- define combinators vs lead headings in sink
- add small image
- add embed video
- add additional sink titles to define different style outputs
- add default left and right margin to blockquote
- float images / items at 100% width until 768px - regular image width default

Check images in particular - what to do with smaller than 100% wide images on mobile for floated images - stretch to fit (editorial expected to use large enough images) / or maintain size until floated?

Also check blockquote. Added side padding as default - removed when floated (using margins instead).

Heading combinators also used - not in sketch.

Padding vs. margin not always matching sketch - not sure if we want to update sketch or not - more of FYI.

Hopefully, adding more descriptor headings helps define the original markup output intentions.

**Comment by joesnellpdx** [comment]
This has been merged

**Pull request merged**
