### PR TITLE
feature/#306-list-component-refinements

### PR DESCRIPTION
**Pull request by joesnellpdx**
Update list item styles to match sketch updates (initial pass)

Desktop: https://share.goabstract.com/e27e2e39-dc2e-4dfb-aa43-5583ee6ffc8f

Mobile: https://share.goabstract.com/5669400f-8408-4788-ad3d-65abdbf5871a

* have to gulp in library
* See library sink pages to view updates:
`/sink-pages/components/lists.html`
`/sink-pages/components/list-sizes.html`
`/sink-pages/components/list-grids.html`

### CODE REVIEW

**Comment by joesnellpdx** [comment]
@ismaeltoure7 

I left some comments in Abstract regarding margins, avatars, and spacing.

I updated based on what I _think_ you were referring to in Sketch. If nothing else, this will give us a point of reference. 

See the description of the MR for where to look.

**Comment by joesnellpdx** [comment]
@ismaeltoure7 All current open questions answered in Abstract and are live in this branch and ready for your review. 

CC: @lauralvictor

**Comment by lauralvictor** [comment]
@ismaeltoure7 May I please be granted access in GoAbstract so that I may compare these changes against the design? Thanks!

**Comment by ismaeltoure7** [comment]
@lauralvictor invite sent.

**Comment by ismaeltoure7** [comment]
Thanks @joesnellpdx It looks great!

I have a few minor updates:
Desktop
- Reduce the margin-top of meta, caption and link to 4px
screen shot 2019-02-13 at 10 45 55 am
screen shot 2019-02-13 at 10 46 06 am
screen shot 2019-02-13 at 10 46 32 am

Desktop and mobile
- For List Avatar items, use an inset divider
screen shot 2019-02-13 at 10 46 59 am
screen shot 2019-02-13 at 10 47 23 am

**Comment by lauralvictor** [comment]
@ismaeltoure7 Thanks! I've just reviewed.

**Comment by lauralvictor** [comment]
@joe on List Grid http://localhost:3000/sink-pages/components/list-grids.html the 4up examples are being cutoff: https://www.evernote.com/l/AZM5i2Ln1UNOSob4ljYjsERSRs_kd6I1CGE

**Comment by joesnellpdx** [comment]
@lauralvictor @ismaeltoure7 

Per Laura's comments: on the list sizes page and the lists grid page - this is showing the lack of resiliency when the items are squished too far. Working as expected until custom styles are implemented (if needed / desired) when the list items are contained within these configurations. @ismaeltoure7 something you may want to put on your radar. 

@ismaeltoure7 margins / avatar items updated.

**Comment by ismaeltoure7** [comment]
@joesnellpdx I understand the concern around resiliency, but I can't think of a scenario requiring 3 column list items. The updates look great. Thx

**Comment by joesnellpdx** [comment]
@lauralvictor Waiting for your 2nd review. See comments above regarding resiliency.

**Pull request merged**
