### PR TITLE
Feature/#135 homepage doc site

### PR DESCRIPTION
**Pull request by joesnellpdx**
Woo-hoo!

- Create doc site home page
- Update shell pages per design files

See issue for more detail:
https://github.com/JDRF/spirit/issues/136#issuecomment-473414370

In library:
- Issue https://github.com/JDRF/spirit/issues/374 resolved: `/sink-pages/components/forms.html` -- no padding left and right on legends
- Issue https://github.com/JDRF/spirit/issues/373 resolved: `/sink-pages/components/long-form-text.html` -- no extra margin on buttons that are not links

In doc site (after library compiled):
-- npm run unlink-local-library
-- npm run link-local-library
-- gulp

- issue https://github.com/JDRF/spirit/issues/375 resolved: `/visual-style/icons.html` see `jdrf` icon (also JDRF  icon in header)
- Doc home page for main updates and secondary pages for hamburger nav (small med screens) and style updates to match new designs

### CODE REVIEW

**Comment by joesnellpdx** [comment]
@ismaeltoure7 

I updated margin top on the JDRF logo - it is a custom number due to the 'link padding,' but aligns with the page title.

I'm re-requesting a review from you to visit again when we have the live content and after any updates I do from our upcoming critique are added. 

So, let us wait for 'sign off' until this is approved to merge. 
Thanks!

**Comment by joesnellpdx** [comment]
@ismaeltoure7 

Please review the latest updates:

- [ ] - Home page logo closer to top of page (already had it this way - but please verify it is correct)
- [ ] - Removed top padding for all content block first headlines - to match height of TOC (although line height drops it down a little -- EightShapes has a mixin to help correct this - maybe something to look at post 1.0.0)
- [ ] - Add bottom margin to intro block - increase vertical spacing between it and the content block
- [ ] - Moved some content around so each content block begins with a heading
- [ ] - Updated TOC styles to _better_ match vertical navigation (although still a bit unique)

Waiting on direction on the following:
- Spirit home page brush (either larger brush or confirm existing is good)
- Spirit home page vertical spacing with `.spirit-subhead` margin bottom at 32px - do we want to make adjustments here - maybe more space between brush and subhead?
- Spirit home page - using animated link instead of minimal button - less vertical spacing, no horizontal spacing - please confirm this is what is expected
- Principles - need content or direction on removing for 1.0.0

**Comment by ismaeltoure7** [comment]
@joesnellpdx I updated your comment above, and here are a few things to update or discuss in crit:
- Logo
- [ ] - Increase size of logo to 116x32px
- [ ] - Remove padding-left
- [ ] - Remove hover state**

- Principles
- [ ] - Header: reduce margin-bottom to 16px
- [ ] - Subhead: update width to 10cols
- [ ] - Increase space between subhead and first principle to 96px**

- Depth: elevation table is crashing into TOC
- Lists: Should we move the top image to the first section?
- Grid: Same as list
- LFT: Should we move the intro paragraph into the first section?

**Comment by joesnellpdx** [comment]
@ismaeltoure7 

I think I can act on all your requests - they make total sense.

I only have questions on the logo, here is what I _think_ you are asking:

1) Remove padding on HOME only but adjust to keep vertical spacing as it is (visually)
2) Remove hover everywhere (home and internal pages) - although it _should_ have an active and hover state for accessibility - I think we can put a pin in this
3) Logo size (internal and home) - desktop IS now 116.22px x 32px - so keep that?

If there are further questions, we can review in a critique

**Comment by joesnellpdx** [comment]
@ismaeltoure7 

Ready to re-review. The updates we discussed have been made. 

One item of note:
Elevation grid, I change the font size to `spirit-body-text-s` to fit the table within the content area. I prefer this to escaping the content area. Let me know if you want to revert to what it was. 

@kevinmpowell 
Are you able to provide a review here? If so, super appreciated!

**Comment by ismaeltoure7** [comment]
> One item of note:
> Elevation grid, I change the font size to `spirit-body-text-s` to fit the table within the content area. I prefer this to escaping the content area. Let me know if you want to revert to what it was.

@joesnellpdx It all looks good, except that I no longer see the "@include..." copy in the grey and blue shadow tables...
Screen Shot 2019-03-28 at 4 32 27 PM

**Comment by joesnellpdx** [comment]
@ismaeltoure7 

Those did not have the `@include` mixins below the elevation examples - it was only in the first - primary example. That being said, I can see why having it here adds more clarity. 

I have added, but used the base font size as it fits here now. Let me know if you have suggestions or further requests.

**Comment by ismaeltoure7** [comment]
@joesnellpdx Looks good. Thx!

**Comment by ismaeltoure7** [comment]
@joesnellpdx @patrickmckowen Homepage with updated copy: https://share.goabstract.com/e8dfb076-a81d-4b2c-bf39-42004d37aa62

**Comment by joesnellpdx** [comment]
@ismaeltoure7 
- Updated card content
- Removed principles

Is this ready to sign off?

**Comment by ismaeltoure7** [comment]
@joesnellpdx Looks good to me. @patrickmckowen thoughts?

**Comment by patrickmckowen** [comment]
@joesnellpdx @ismaeltoure7 looks beautiful.  One piece of feedback: your computer screen needs to be at least 1,000px tall to see the cards.  And the hero gives the impression of a "false bottom" https://mrkr.io/s/5ca21d9fedda10598ba03aef/0

**Comment by joesnellpdx** [comment]
@patrickmckowen 

That is similar to some of the other existing layouts like the I'm the Type Page:
https://www.jdrf.org/community/take-action/imthetype/

Any design ideas to improve that in a way that fits JDRF / Spirit?

Here are some I found this morning:
https://webflow.com/blog/breaking-the-illusion-of-completeness
https://www.uxbooth.com/articles/best-practices-for-scrolling/

Or... something we should ponder post 1.0.0?

**Comment by joesnellpdx** [comment]
@ismaeltoure7 

Updated text. Remove the Pally line and also removed the numbering as only one option exists.

If all else is good:

Comment approved here.
Close your open issues - (Not this one)

**Comment by ismaeltoure7** [comment]
@joesnellpdx Approved.

**Pull request merged**
