### PR TITLE
Feature/177 layout grid build

### PR DESCRIPTION
**Pull request by joesnellpdx**
- add paint options
- add wave options
- create sink pages
- add tokens where needed

### CODE REVIEW

**Comment by joesnellpdx** [comment]
@patrickmckowen @jamesmelzer @kevinmpowell 

This branch is ready for review:
See the following pages:
/sink-pages/components/brushes.html
/sink-pages/components/containers-painted-edge.html
/sink-pages/components/containers-wave-background.html

On wave background page, attempted several ideas to have max with with css and aspect ratio with no agreeable results. Can invest more time if needed, bit recommend adding to backlog if that is the case.

@kevinmpowell 
I need you to look at merging develop into branch -- It will probably be fine if I do it, but I don't want to break the gulp updates and want to make sure they are in their best state moving forward. Ask me if you have any questions.

**Comment by jamesmelzer** [comment]
I'm unclear on the purpose of `spirit-image-block`. Is it just for demo purposes, or is it an implicit component products can use? Can the name reflect if it's a sink-only placeholder thing?

**Comment by jamesmelzer** [comment]
Under "Padding Options" all the painted-edge blocks reset to zero padding at the maximum breakpoint (1480?). I get that they lose their brush at that breakpoint. But why do they also lose the white top/bottom padding?

**Comment by joesnellpdx** [comment]
@jamesmelzer 

1. Replaced `.spirit-image-block` with `.container-sink-demo-component.` I wanted to add this component to test the future build of the split screen hero: https://share.goabstract.com/d0949299-7b4e-4840-af33-33a4b6663d96
2. I removed any 'assumptions' on the `.container-sink-demo-component` after the paint items are gone ( which impacted the how the padding was displaying ). Padding options should be back to normal after the 1480 breakpoint. Also, padding on the 'black' and 'brand' containers is interior not exterior ( without the paint). See `http://localhost:3000/sink-pages/components/containers.html`.
3. 1480 x 96 (12x) is the current size of the svg itself. If we go larger, it will start stretching ( get taller or start getting 'cut off' to maintain the height. During a previous meeting, we discussed not allowing for the stretch.
4. I added more long form text examples to pair with the demo component to show standard display in conjunction.

NOTE on paint size: 
They are actually 1480px x 192px as there are artifacts beyond 96px I want to capture. They are wrapped in a container with overflow hidden that is set to 96px tall (12x) to maintain that height.

CC: @kevinmpowell @patrickmckowen

**Comment by jamesmelzer** [comment]
I definitely wasn’t proposing stretching. I’m wondering is there a downside
to just making a longer asset (add more art, not stretch what we’ve got).
-- 
James Melzer

EightShapes, LLC
james@eightshapes.com
301-651-7719

**Comment by joesnellpdx** [comment]
Adding more art would be a questions for @ismaeltoure7  and @patrickmckowen 

On the front end side, should make a difference so long as the height remains the same.

**Comment by joesnellpdx** [comment]
- added all brushes to brushes sink page: `/sink-pages/components/brushes.html`
- displaying wave3, wave4, and wave5 on sink for waves: `/sink-pages/components/containers-wave-background.html`
- waves are now 100% height of container with max width depending on width in sketchfile
- code cleanup

@jamesmelzer @kevinmpowell @patrickmckowen 

Kevin - need you to assist with merge conflicts per comment above (gulp tasks) - https://github.com/JDRF/spirit/pull/242#issuecomment-417111955

**Comment by jamesmelzer** [comment]
I don't see any issues. Approved. I'm writing the brushes section of the Container doc based on this version.

**Comment by JodiWarren** [comment]
@joesnellpdx I've added the font loading class refactor to this PR.

**Comment by joesnellpdx** [comment]
@kevinmpowell 

Jodi added mixin `@mixin spirit-load-fonts()` to my branch that does not render Graphik without loader setup complete via typography.js. I think he did it to allow for font loading by component rather than globally - but it feels to me it should be a base body style?

Additionally, where did we land on that with the doc site and for production? Is this going to break stuff? Should we remove it altogether?

I may be dead in the brain as it is Friday but want to make sure I get this into a conversation before I forget. 

SEE:
https://github.com/JDRF/spirit/pull/242/commits/e5c7448d53f93c90a79976558dc937e1c65f44a7

Since have added that mixin where needed in the library (i.e. the index.njk )

**Comment by patrickmckowen** [comment]
@joesnellpdx looks great!

**Pull request merged**
