### PR TITLE
Feature/#308 update scripting and documentation

### PR DESCRIPTION
**Pull request by joesnellpdx**
For library:
1. Switch to `/library`
2. `npm install`
3. `gulp`

For doc-site ( after library compiled ):
1.  Switch to `/doc-site`
2. `npm run unlink-local-library`
3. `npm run link-local-library`
4. `gulp`

For doc site:

- Library: [Document adding component scripts to project](https://docs.google.com/document/d/1x2LD7WXbNgLsQLwguTk7qZjeGcoLECRAqA7bJB9gDSo/edit?usp=sharing)
- Library: [Document adding dependencies](https://docs.google.com/document/d/1x2LD7WXbNgLsQLwguTk7qZjeGcoLECRAqA7bJB9gDSo/edit?usp=sharing)
- Library: [Document adding scripts and/or dependencies to sink page](https://docs.google.com/document/d/1x2LD7WXbNgLsQLwguTk7qZjeGcoLECRAqA7bJB9gDSo/edit?usp=sharing)
- Doc-site: Document using Spirit global scripts - not using global script on doc site
- Doc-site: [Document adding Spirit script dependencies](https://docs.google.com/document/d/1x2LD7WXbNgLsQLwguTk7qZjeGcoLECRAqA7bJB9gDSo/edit?usp=sharing)
- Doc-site: [Document adding scripts and/or dependencies to doc site page](https://docs.google.com/document/d/1x2LD7WXbNgLsQLwguTk7qZjeGcoLECRAqA7bJB9gDSo/edit?usp=sharing)
- Doc-site: update scripting documentation. In [GDocs](https://docs.google.com/document/d/1izGQJbckd99tjsSO63f1ExUanFH7ox5gRJwG9V2bSRg/edit#) and in doc site files included in this MR. 
- For External: Add new gulp tasks to minify spirit scripts
- For External: Add new gulp task to combine and minify spirit scripts and dependencies - created spirit.js, spirit.dependencies.js, and spirit.bundle.js.
- For External: Scripts found in locations described in [new doc](https://docs.google.com/document/d/1x2LD7WXbNgLsQLwguTk7qZjeGcoLECRAqA7bJB9gDSo/edit?usp=sharing)
- For External: CDN updates added to [another issue](https://github.com/JDRF/spirit/issues/310)

The following doc have also been updated:
[Getting Started for Developers](https://docs.google.com/document/d/1izGQJbckd99tjsSO63f1ExUanFH7ox5gRJwG9V2bSRg/edit?usp=sharing) - needs review
[System Architecture & Coding Standards](https://docs.google.com/document/d/1AaVdH8dldIaHFQuD65MQSZkzLAUrMCBY3PZE5C9gEF0/edit?usp=sharing) - needs review

Things to test in Spirit:
1. Library (after following the steps at the top of the description): `library/_site/latest/scripts` AND `library/dist/` contain the following:
* `spirit.js`, `spirit.min.js`
* `spirit.bundle.js`, `spirit.bundle.min.js`
* `spirit.dependencies.js`, `spirit.dependencies.min.js`
2. Library: The new sink page `/sink-pages/components/pagebundle.html` found at the bottom of the library index page - should work as expected. It is using `spirit.bundle.min.js` - see the end of the file for form field masks
3. Doc site (after following the steps at the top of the description): scrips listed in 1. should be found in `doc-site/docs/scripts` -- these are what will be found at `jdrf.design` (and eventually on CDN).
4. Review updates on `/getting-started.html#external-dependencies` under Javascript. Same changes also found in [GDocs](https://docs.google.com/document/d/1izGQJbckd99tjsSO63f1ExUanFH7ox5gRJwG9V2bSRg/edit#). 

Please review document updates and general code updates (see 'files changed' and list of changes above).
Add comments in code (files changed above) or directly in this thread. 
Please let me know if you have any questions.

The CDN links are not active yet.
Some of this I won't be able to fully test until the release is live - although I am confident in the result.

### CODE REVIEW

**Comment by joesnellpdx** [comment]
@patrickmckowen I have assigned to you to this task to minimally review the doc site javascript documentation updates. 

@lauralvictor & @ismaeltoure7 will review the rest. 

Let me know if you have questions

**Comment by joesnellpdx** [comment]
@patrickmckowen @ismaeltoure7 

Made some minor adjustments to doc_site - primarily adding links to cdn scripts (which will be available soon):
https://github.com/JDRF/spirit/pull/311/commits/a3e6b7eebc8c4d478ce7847092cb9f5eacc165ad

Do we want to merge for release alpha 5 or hold for 1.0.0?

**Comment by patrickmckowen** [comment]
@joesnellpdx unless there is a pressing need for it, I suggest we include it in 1.0.

**Comment by joesnellpdx** [comment]
@patrickmckowen Sounds good. Will hold on merging until alpha 5 is released.

**Comment by joesnellpdx** [comment]
@kevinmpowell Adding you as a reviewer for this ticket. Would love your feedback.

**Comment by kevinmpowell** [comment]
@joesnellpdx this looks good. Exactly the type of thing I'd do if I needed to alter the way esds-build handles JS.

**Pull request merged**
