### PR TITLE
Feature/222  site nav toggles

### PR DESCRIPTION
**Pull request by kevinmpowell**
@joesnellpdx can you take a look at this and solve for the `vertical_navigation.js` issues I mentioned?
1. It takes two clicks to collapse one of the site nav menus
2. Clicking once one collapsible and then clicking a _different_ collapsible closes the _first_ collapsible. 
3. At that point clicking different collapsibles seems to trigger others. The click event mapping doesn't seem locked into the target that was just clicked on.

### CODE REVIEW

**Comment by joesnellpdx** [comment]
@kevinmpowell 

Pushed update to resolve issue:

- one click to close
- if multiple open ( expanded ) - closing one does not close all

SEE:
https://github.com/JDRF/spirit/pull/230/commits/1983f773678864d5efbc4966225cb8eb83f62c5c

Assigning back to you

**Comment by kevinmpowell** [comment]
@joesnellpdx this looks great. I assume you can sign off on final review?

**Comment by jamesmelzer** [comment]
looking now...

**Comment by jamesmelzer** [comment]
Works well with Joe's "one-click" commit. Approved.

**Pull request merged**
