### PR TITLE
Feature/#307 card component refinements

### PR DESCRIPTION
**Pull request by joesnellpdx**
Style updates from design refinements.

See: 
Desktop: https://share.goabstract.com/bc46eaa8-5e95-4b47-a4b7-6bf2a8aa5192

Mobile: https://share.goabstract.com/e6328374-7be3-42ab-b0f9-ace74a6482e9

**NOTES**
* Margin / padding between image and text is void on .org due to override in figure styles - need ticket in .org to fix (can be with post 1.0.0 Spirit consumption on .org)
* Card items with and without image is not a class difference - so the component can't have different styles at this point based on that factor. This is something to discuss if an issue.
* Truncation of the body text was requested on small screens only. I _highly_ recommend against adding javascript within Spirit for that. I have added some css that does it on some browsers, but kind of looks 'broken' on others (see Firefox). Alternatives: 1) fade to white instead of ellipsis with max height, 2) truncate on all screens but have as a requirement (DO) for properties consuming Spirit, 3) leave as is (remove new change)
* Divider: there is a request for some items to have a 'divider', similar to list items, under the content in lieu of the box shadow, then switching to box shadow on hover. We discussed this in our original creation of the card having technical challenges with an element that looks correct and also transitions into the box shadow reliably. If this is required, we can explore other options. Due to having this conversation earlier & the new addition of the initial elevation - using the initial elevation for now.

### CODE REVIEW

**Comment by joesnellpdx** [comment]
@ismaeltoure7 See abstract comments in addition to PR description. I am anticipating conversation.

**Comment by joesnellpdx** [comment]
@ismaeltoure7 

Ready for your review.

- [ ] - Look on mobile at the two list components. 
1) I was able to do the divider if an image is present - please verify spacing
2) the list item with no image has border with border radius - so different implementation with different spacing - I know not part of the abstract file, but please review as well

- [ ] - Figure: reduced bottom margin to 8px - Gauri will be adding .org ticket to wrike for bug fix there
- [ ] - I believe the rest of our Abstract communication has been resolved. Tried to close / delete annotations, but did it wrong in Abstract - sorry about that!

LMK if you have further questions

**Comment by ismaeltoure7** [comment]
@joesnellpdx Great job!!! I only have a few minor comments. Feel free to put some time on my calendar if you'd like to discuss options for the spacing between the Mobile List Cards.

**Desktop**
_Large_
- Title: reduce margin bottom to 8px
_Small_
- Title: use H5

**Mobile**
_Stack + Text_
- Title: update line height to 20px (H4)
- List: reduce to space between cards (if possible)

**Comment by lauralvictor** [comment]
@joesnellpdx I'll hold off review until @ismaeltoure7 's recommended changes are completed.

**Comment by joesnellpdx** [comment]
@ismaeltoure7 

VERY important you reviews my initial MR comments regarding truncation. I think what I've done is a bit hacky and I think not truncating the text is the ideal option. We can discuss this further if needed.

I see your previous style requests and will address soon.

**Comment by joesnellpdx** [comment]
@ismaeltoure7 

Updates discussed have been pushed.
- Removed truncation
- Updating font sizes and line heights mentioned above
- Updated spacing for list card items

**Comment by ismaeltoure7** [comment]
@joesnellpdx still seeing a few issues...

**Desktop**
_Large_
* Title: reduce margin bottom to 8px
screen shot 2019-02-14 at 4 44 42 pm


**Mobile**
_Stack + Text_
* Title: update line height to 20px (H4)
screen shot 2019-02-14 at 4 45 21 pm

**Comment by joesnellpdx** [comment]
@ismaeltoure7 

* Title margin updated on large card
* Mobile stack and text - line height is 1.25 (same as 20px for font size) - stack was off and now fixed

**Pull request merged**
