### PR TITLE
Feature/#315 card object fit refactor

### PR DESCRIPTION
**Pull request by joesnellpdx**
Card object fit was not working in the wild - using 'correct' image sizes created illusion it was working correctly. This fixes the issue. 

- absolutely position object-fit image
- test xbrowser - did not include polyfill in branch
- add image ratio sizes to tokens
- changed default image to square 800x800 image for testing
- add raw object-fit polyfill to cards grid sink page

To test:

1) Go to `/sink-pages/components/card-grids.html`
2) Make sure 800x800 image text looks the same as the raw image from `/images/components/container/800x800.png` (it is not stretched)
3) Open page on ie11 - make sure images all look correct - not warped or stretched

Note - will not work with captions, but captions not intended in card

Will require refactoring on .org - will request ticket

### CODE REVIEW

**Comment by lauralvictor** [comment]
@joesnellpdx What is the QA process for testing this change?

**Comment by joesnellpdx** [comment]
@lauralvictor I updated the MR description to include some testing steps and some enhancements to make testing easier.

**Comment by lauralvictor** [comment]
@joesnellpdx Thanks for the instructions.

**Comment by joesnellpdx** [comment]
@kevinmpowell 

Review the list MR first - as it includes this one:
https://github.com/JDRF/spirit/pull/358

**Pull request merged**
